spring.application.name=airline-ticket-reservation-system

server.port=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=

# Gmail SMTP Configuration
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=

# JWT Configuration
jwt.secret=e.g.8c3f1a94b0e84d7fab2c4fe7f1a2c9e9a44d957a1d3b4c0c8e6fbb9da73e42f5
# 1 hour verification token expiration
jwt.verification.expiration=3600000

# Application Base URL
app.base.url=https://client-app-base-url