#
#spring.application.name=airline-ticket-reservation-system
#
#server.port=9090
#
#spring.datasource.url=jdbc:mysql://localhost:3306/airline_db
#spring.datasource.username=root
#spring.datasource.password=Genpact@123456789
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## Gmail SMTP Configuration
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=587
#spring.mail.username=5a7215834325ef
#spring.mail.password=077fcdc9ac0e37
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## JWT Configuration
#jwt.secret=e.g.8c3f1a94b0e84d7fab2c4fe7f1a2c9e9a44d957a1d3b4c0c8e6fbb9da73e42f5
## 1 hour verification token expiration
#jwt.verification.expiration=3600000
#
## Application Base URL
#app.base.url=http://localhost:3000

spring.application.name=airline-ticket-reservation-system

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/airline_db
spring.datasource.username=root
spring.datasource.password=Genpact@123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Gmail SMTP Configuration
spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=genpactcapstoneatrs2025@gmail.com
#spring.mail.password=prxcwmdicrqwtcdn
#spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
#spring.mail.username=5a7215834325ef
#spring.mail.password=077fcdc9ac0e37
spring.mail.username=genpactcapstoneatrs2025@gmail.com
spring.mail.password=prxcwmdicrqwtcdn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.debug=true

# JWT Configuration
jwt.secret=8c3f1a94b0e84d7fab2c4fe7f1a2c9e9a44d957a1d3b4c0c8e6fbb9da73e42f5
# 1 hour verification token expiration
jwt.verification.expiration=3600000

# Application Base URL
app.base.url=http://localhost:3000