spring.application.name=airline-ticket-reservation-system

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/atrs_db
spring.datasource.username=root
spring.datasource.password=Root@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Gmail SMTP Configuration
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=9e5f18dba5e185
spring.mail.password=3edc9eb089dbe4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=e.g.8c3f1a94b0e84d7fab2c4fe7f1a2c9e9a44d957a1d3b4c0c8e6fbb9da73e42f5
# 1 hour verification token expiration
jwt.verification.expiration=3600000

# Application Base URL
app.base.url=http://localhost:3000